spring:
    datasource:
        name: orcl
        url: jdbc:mysql://120.78.192.139:3306/zpp_note?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
        username: root
        password: zjc123456
#         使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
    file: logs/user-manager.log
    level:
        root: INFO
        tk.mybatis: TRACE
        com.basedata: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic
feign.hystrix.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
